source/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    # ORDER.
    path('<int:choice>', views.order_page, name="order-page"),
    path('cancel-order/<int:pk>', views.cancel_order, name='cancel-order'),
    # PRODUCT DETAIL.
    path('buy-now/', views.buy_now, name='buy-now'),
    path('product/<int:pk>', views.product_detail, name='product'),
    path('purchase-cart/<int:pk>', views.purchase_cart, name='purchase-cart'),
    # CART.
    path('cart/', views.cart_page, name='cart-page'),
    path('create-cart/<int:pk>', views.create_cart, name='create-cart'),
    path('update-cart/<int:pk>', views.update_cart, name='update-cart'),
    path('delete-cart/<int:pk>', views.delete_cart, name='delete-cart'),
    path('create-order/', views.create_order, name="create-order")
]

source/profiles/urls.py
from django.urls import path

from . import views
from controls.views import home_page


urlpatterns = [
    # HOME PAGE.
    path('', home_page, name='home'),
    # SYSTEM FUNCTIONS.
    path('signin/', views.signin_page, name='signin'),
    path('signup/', views.signup_page, name='signup'),
    path('logout/', views.logout_page, name='logout'),
    path('forgot/', views.forgot_page, name='forgot'),
    # TOKEN ACTIVATION.
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('reset/<uidb64>/<token>', views.reset_password, name='reset'),
    # USER INFORMATION.
    path('profile/<int:choice>', views.profile_page, name='profile'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('change-password/', views.change_password, name='change-password'),
    path('manage-address/', views.create_or_update_address, name='manage-address'),
    path('delete-address/', views.delete_address, name='delete-address'),
    # CHATBOT.
    path('chatting/', views.chatting, name='chatting'),
    path('getChat/', views.getChat, name='getChat'),
    path('thumbsup/', views.thumbsup, name='thumbsup'),
    path('thumbsdown/', views.thumbsdown, name='thumbsdown'),
]

source/webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('profiles.urls')),
    path('orders/', include('orders.urls')),
    path('controls/', include('controls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_shipper = models.BooleanField(default=False)
    first_name = None
    last_name = None

    @property
    def role(self) -> str:
        return 'Vận chuyển' if self.is_shipper else 'Bán hàng'


class Person(models.Model):
    last_name = models.CharField(max_length=50, null=True, blank=True)
    first_name = models.CharField(max_length=25, null=True, blank=True)
    gender = models.BooleanField(null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.PROTECT)

    class Meta:
        abstract = True

    def __str__(self) -> str:
        return f'{self.last_name} {self.first_name}'

    @property
    def fullname(self) -> str:
        return f'{self.last_name} {self.first_name}'


class Employee(Person):
    address = models.TextField(null=True, blank=True)
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    salary = models.DecimalField(max_digits=10, decimal_places=2)
    is_quit = models.BooleanField(default=False)


class Customer(Person):
    pass

source/profiles/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User, Customer


class SignInForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username', 'class': 'log-input-field'
    }), required=True)

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password', 'class': 'log-input-field'
    }), required=True)

    class Meta:
        model = User
        fields = '__all__'


class SignUpForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Username', 'class': 'log-input-field'
    }), required=True)

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Email', 'class': 'log-input-field'
    }), required=True)

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password', 'class': 'log-input-field'
    }), required=True)

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Password Confirmation', 'class': 'log-input-field'
    }), required=True)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class PersonalForm(forms.ModelForm):
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'ml-4 p-2 border-2 rounded-lg'
    }), required=False)

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'ml-4 p-2 border-2 rounded-lg'
    }), required=False)

    gender = forms.BooleanField(widget=forms.RadioSelect(attrs={
        'class': 'flex ml-4 gap-10'
    }, choices=((True, 'Nam'), (False, 'Nữ'))), required=False)

    birthdate = forms.DateField(widget=forms.DateInput(attrs={
        'type': 'date', 'class': 'ml-4 p-2 border-2 rounded-lg'
    }), required=False)

    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

source/profiles/views.py
from webapps import sessions
from django.http import HttpRequest, HttpResponse
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect, get_object_or_404
# DATA.
from django.db.transaction import atomic
from orders.models import DeliveryAddress
from .models import User, Customer
from .forms import SignInForm, SignUpForm, PersonalForm
# TOKEN.
from django.utils.encoding import force_str
from django.utils.http import urlsafe_base64_decode
from .tokens import ACCOUNT_ACTIATION_TOKEN
# PERMISSION.
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.decorators import user_passes_test
# CHATBOT.
import json
from Chatbot import ChatBot
import csv
from googletrans import Translator


def check_customer_permission(user: AbstractBaseUser) -> bool:
    return user.is_authenticated and not (user.is_superuser or user.is_staff or user.is_shipper)


# LOGIN, SIGNUP & LOGOUT.
@atomic
def signup_page(request: HttpRequest):
    form = SignUpForm()

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            # CREATE USER.
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            Customer.objects.create(user=user)
            # SEND MAIL.
            ACCOUNT_ACTIATION_TOKEN.send_email(request, user, 'Activate your account', 'email/verification.html')
            # SUCCESS.
            sessions.add(request, 'Đăng ký thành công', 'Hãy kiểm tra email của bạn')
            return redirect('signin')
        else:
            # FAILURE.
            sessions.add(request, 'Đăng ký thất bại', 'Thông tin không hợp lệ', False)

    context = {'form': form, **sessions.get(request)}
    return render(request, 'signup.html', context)


def activate(request: HttpRequest, uidb64: str, token: str):
    # GET DATA FROM TOKEN.
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None
    # VERIFY USER.
    if user and ACCOUNT_ACTIATION_TOKEN.check_token(user, token):
        user.is_active = True
        user.save()
        # SUCCESS.
        sessions.add(request, 'Xác thực thành công', 'Tài khoản của bạn đã được xác thực')
        return redirect('signin')
    else:
        # FAILURE.
        return render(request, 'email/failed_verify.html')


def signin_page(request: HttpRequest):
    if request.user.is_authenticated:
        return redirect('home')

    form = SignInForm(request)
    if request.method == 'POST':
        form = SignInForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('home')
        else:
            sessions.add(request, 'Đăng nhập thất bại', 'Thông tin không chính xác', False)

    context = {'form': form, **sessions.get(request)}
    return render(request, 'signin.html', context)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def logout_page(request: HttpRequest):
    logout(request)
    return redirect('signin')


# FORGOT PASSWORD.
def forgot_page(request: HttpRequest):
    if request.method == 'POST':
        # GET DATA.
        username = request.POST.get('username')
        email = request.POST.get('email')
        # VERIFY USER..
        user = User.objects.filter(username=username, email=email).first()
        if user:
            # SEND MAIL.
            ACCOUNT_ACTIATION_TOKEN.send_email(request, user, 'Reset your password', 'email/reset_password.html')
            # SUCCESS.
            sessions.add(request, 'Thao tác thành công', 'Hãy kiểm tra email của bạn')
            return redirect('signin')
        else:
            # FAILURE.
            sessions.add(request, 'Thao tác thất bại', 'Thông tin không chính xác', False)

    return render(request, 'forgot.html')


def reset_password(request: HttpRequest, uidb64: str, token: str):
    # GET DATA FROM TOKEN.
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except:
        user = None
    # VERIFY USER.
    if user and ACCOUNT_ACTIATION_TOKEN.check_token(user, token):
        if request.method == 'POST':
            password1 = request.POST.get('password1')
            password2 = request.POST.get('password2')
            if password1 == password2:
                user.set_password(password1)
                user.save()
                # SUCCESS.
                sessions.add(request, 'Thao tác thành công', 'Khôi phục mật khẩu thành công')
                return redirect('signin')
            else:
                # FAILURE.
                sessions.add(request, 'Thao tác thất bại', 'Mật khẩu xác nhận không trùng khớp', False)
    else:
        # FAILURE.
        return render(request, 'email/failed_verify.html')

    return render(request, 'reset.html', {**sessions.get(request)})


# PROFILE PAGE.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def profile_page(request: HttpRequest, choice: int):
    customer = request.user.customer
    cart_models = customer.cart_details.all()
    # INFORMATION
    form = PersonalForm(instance=customer)
    # ADDRESS.
    addresses = customer.deliveryaddress_set.all()

    context = {'form': form, 'choice': choice, 'addresses': addresses,
               'cart_models': cart_models, **sessions.get(request)}
    context.update({'addresses': addresses} if choice == 2 else {})
    return render(request, 'profile.html', context)


# INFORMATION.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def update_profile(request: HttpRequest):
    form = PersonalForm(instance=request.user.customer, data=request.POST)
    if form.is_valid():
        form.save()
        sessions.add(request, 'Thao tác thành công', 'Cập nhật thông tin thành công')

    return redirect("profile", 1)


# PASSWORD.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def change_password(request: HttpRequest):
    user = request.user
    password = request.POST.get('password')
    password1 = request.POST.get('password1')
    password2 = request.POST.get('password2')

    if password1 != password2:
        sessions.add(request, 'Thao tác thất bại', 'Mật khẩu xác nhận không trùng khớp', False)
    elif not user.check_password(password):
        sessions.add(request, 'Thao tác thất bại', 'Mật khẩu cũ không chính xác', False)
    else:
        user.set_password(password1)
        user.save()
        login(request, user)
        sessions.add(request, 'Thao tác thành công', 'Thay đổi mật khẩu thành công')

    return redirect("profile", 4)


# ADDRESS.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def create_or_update_address(request: HttpRequest):
    fullname = request.POST.get('fullname')
    phone = request.POST.get('phone')
    number = request.POST.get('number')
    province, district, communce = request.POST.get(
        'province'), request.POST.get('district'), request.POST.get('commune')
    address = (f'{number}, ' if number else '') + f'{communce}, {district}, {province}'

    customer = request.user.customer
    if (pk := int(request.POST.get("pk"))) == -1:
        DeliveryAddress.objects.create(
            fullname=fullname, phone=phone, address=address, customer=customer)
    else:
        DeliveryAddress.objects.filter(pk=pk).update(
            fullname=fullname, phone=phone, address=address, customer=customer)

    return redirect('profile', 2)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def delete_address(request: HttpRequest):
    address = get_object_or_404(DeliveryAddress, pk=request.POST.get('pk'))
    address.delete()
    return redirect('profile', 2)


# CHATBOT.
def chatting(request: HttpRequest):
    data = json.loads(request.body)
    message = data.get('message', '')
    context=""
    if request.session.get('context') != None:
        context = request.session.get('context')
    response = ChatBot.chat(message, context)
    if response[2]!="":
        request.session['context'] = response[2]
    if request.session.get('chat') == None:
        request.session['chat'] = [[message, response]]
    else:
        chat = request.session.get('chat')
        chat.append([message, response])
        request.session['chat'] = chat
    response_data = json.dumps(response)
    return HttpResponse(response_data, content_type='json')


def getChat(request: HttpRequest):
    if request.session.get('chat') == None:
        chat=[]
    else:
        chat = request.session.get('chat')
    response_data = json.dumps(chat)
    return HttpResponse(response_data, content_type='json')


def thumbsup(request: HttpRequest):
    data = json.loads(request.body)
    translator = Translator()
    message = translator.translate(data.get('message', '')).text
    label = data.get('label', '')
    if label =="":
        response_data = json.dumps("")
        return HttpResponse(response_data, content_type='json')
    labelExist=False
    with open("Chatbot/record/understand.json") as file:
        data = json.load(file)
    for intent in data["intents"]:
        if intent["tag"] == label:
            if message not in intent["patterns"]:
                intent["patterns"].append(message)
                labelExist=True
    if not labelExist:
        dictd={
            "tag": label,
            "patterns": [
                message
            ],
        }
        data["intents"].append(dictd)
    with open("Chatbot/record/understand.json", "w") as file:
        json.dump(data, file)

    response_data = json.dumps("")
    return HttpResponse(response_data, content_type='json')


def thumbsdown(request: HttpRequest):
    data = json.loads(request.body)
    translator = Translator()
    message = translator.translate(data.get('message', '')).text

source/profiles/templates/customer/address.html
{% load static %}


<!-- Form -->
<div class="mx-4 py-3 flex flex-col gap-5 font-main">
    <button class="buyButtons w-fit bg-green-300 rounded-xl px-4 py-3 hover:text-white ml-auto">
        <i class="fa-solid fa-circle-plus"></i> Thêm mới
    </button>
	<!-- Addresses -->
    <div class="mt-2 space-y-5">
        {% for address in addresses %}
            <div class="flex px-5 py-3 justify-between bg-secondary rounded-xl">
                <div class="w-max">
                    <div class="flex gap-10">
                        <p class="name">
							<i class="fa-solid fa-universal-access text-xl"></i>
							{{ address.fullname }}
						</p>
                        <p class="phone">
							<i class="fa-solid fa-square-phone text-xl"></i> 
							{{ address.phone }}
						</p>
                    </div>
                    <p class="address mt-3">
						<i class="fa-solid fa-map-location-dot text-xl"></i> 
						<span class="address">{{ address.address }}</span>
					</p>
					<span class="hiddenAddress hidden">{{ address.address }}</span>
                </div>
                <div class="w-fit space-x-6">
                    <button class="w-36 ml-[1.5rem] mb-2 p-2 rounded-lg bg-sky-300 hover:text-white updateBtn">Cập nhật</button>
					<form action="{% url "delete-address" %}" method="post" id="deleteFrm" onSubmit="return confirm('Bạn có muốn xóa địa chỉ này?')">
						{% csrf_token %}
						<button value="{{ address.pk }}" name="pk" type="submit" class="inline-block w-36 p-2 rounded-lg bg-red-300 text-center hover:text-white">Xóa</button>
					</form>
                </div>
            </div>
            {% empty %}
            <p class="p-5 text-center italic">Bạn chưa thiết lập địa chỉ giao hàng nào!</p>
        {% endfor %}
    </div>
</div>
<!-- Address Modal -->
<div id="myModal" class="invisible min-w-[50vw] min-h-[50vh] left-1/4 top-32 fixed bg-gray-300 rounded-lg overflow-hidden">
	<form action="{% url "manage-address" %}" method="post">
		{% csrf_token %}
		<div class="flex justify-between text-white bg-indigo-500">
			<h3 class="p-3 pl-5 italic"><i class="fa-solid fa-truck-fast"></i> Địa chỉ giao hàng</h3>
			<button id="closeModal" class="px-5 py-3 hover:bg-red-500"><i class="fa-solid fa-xmark"></i></button>
		</div>
		<div class="p-5">
			<div class="chooseAdd space-y-5">
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Họ tên: </span>
					<input id="nameInput" type="text" name="fullname" class="w-3/5 p-2 rounded-md" required>
				</div>
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Số điện thoại: </span>
					<input id="tel"type="tel" name="phone" class="w-3/5 p-2 rounded-md" required>
				</div>
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Thành phố/Tỉnh: </span>
					<select id="dropdownProv" class="w-3/5 p-2 rounded-md" name="province" required></select>
					<input type="hidden" >
				</div>
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Quận/Huyện: </span>
					<select id="dropdownDistr" class="w-3/5 p-2 rounded-md" name="district" required></select>
					<input type="hidden" >
				</div>
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Phường/Xã: </span>
					<select id="dropdownWard" class="w-3/5 p-2 rounded-md" name="commune" required></select>
					<input type="hidden" >
				</div>
				<div class="flex gap-3 items-center justify-center">
					<span class="w-1/5">Số nhà: </span>
					<input id="houseNum" type="text" name="number" class="w-3/5 p-2 rounded-md">
				</div>
			</div>
		</div>
		<button type="submit" name="pk" id="submitBtnModal" value="-1" class="btnConfirm block w-36 rounded-full mx-auto my-5 p-3 bg-indigo-500 text-white">Xác nhận</button>
	</form>
</div>
<!-- Modal Script -->
<script src="{% static "js/address.js" %}"></script>

source/profiles/templates/customer/change_password.html
<!-- Form -->
<form action="{% url "change-password" %}" method="post" class="w-3/5 mx-4 py-3 flex flex-col gap-5">
    {% csrf_token %}
    <input type="hidden" name="choice" value={{ choice }}>

    <table class="border-separate border-spacing-4">
        <tr>
            <td class="text-right">Mật khẩu cũ: </td>
            <td><input type="password" name="password" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
        <tr>
            <td class="text-right">Mật khẩu mới: </td>
            <td><input type="password" name="password1" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
        <tr>
            <td class="text-right">Mật khẩu xác nhận: </td>
            <td><input type="password" name="password2" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
    </table>

    <button type="submit" class="w-1/4 mx-auto mt-5 p-2 rounded-lg bg-sky-300 text-white hover:shadow-lg">
        <i class="fa-solid fa-cloud-arrow-up"></i> Lưu
    </button>
</form>

source/profiles/templates/customer/user_profile.html
{% load static %}


<!-- Form -->
<div class="flex">
    <!-- Information -->
    <form action="{% url "update-profile" %}" method="post" class="w-3/5 mx-4 py-3 flex flex-col gap-5">
        {% csrf_token %}
        <input type="hidden" name="choice" value={{ choice }}>
        
        <div class="flex justify-between">
            <div>
                <label for="id_last_name">Họ </label>
                {{ form.last_name }}
            </div>
            <div>
                <label for="id_first_name">Tên </label>
                {{ form.first_name }}
            </div>
        </div>
        <div class="flex">
            <label for="id_gender">Giới tính </label>
            {{ form.gender }}
        </div>
        <div>
            <label for="id_birthdate">Ngày sinh </label>
            {{ form.birthdate }}
        </div>
        <div>
            <label for="id_birthdate">Email </label>
            <input type="email" value="{{ request.user.email }}" class="w-1/2 ml-14 p-2 outline-none rounded-lg bg-gray-200" readonly>
        </div>
        <button type="submit" class="w-1/4 mx-auto mt-5 p-2 rounded-lg bg-sky-300 text-white hover:shadow-lg">
            <i class="fa-solid fa-cloud-arrow-up"></i> Lưu
        </button>
    </form>
    <!-- Avatar -->
    <div class="w-2/5 self-center">
        <img src="{% static "img/avatar.svg" %}" class="w-48 mx-auto">
    </div>
</div>