source/controls/urls.py
from django.urls import path

from . import views


app_name = 'controls'
urlpatterns = [
    # SYSTEM FUNCTIONS.
    path('dashboard/signin/', views.dashboard_signin, name='signin'),
    path('dashboard/logout/', views.dashboard_logout, name='logout'),
    path('dashboard/change-password/', views.dashboard_password, name='change-password'),
    # DASHBOARD PAGE.
    path('dashboard/employee/', views.dashboard_employee, name='employee'),
    path('dashboard/product/', views.dashboard_product, name='product'),
    path('dashboard/reservation/', views.dashboard_reservation, name='reservation'),
    path('dashboard/importation/', views.dashboard_importation, name='importation'),
    path('dashboard/order/', views.dashboard_order, name='order'),
    # EMPLOYEE.
    path('dashboard/employee/create/', views.create_employee, name='create-employee'),
    path('dashboard/employee/update/<int:pk>', views.update_employee, name='update-employee'),
    # PRODUCT.
    path('dashboard/specification/create/', views.create_specification, name='create-specification'),
    path('dashboard/product/create/', views.create_product, name='create-product'),
    path('dashboard/product/update/<int:pk>', views.update_product, name='update-product'),
    path('dashboard/product/delete/<int:pk>', views.delete_product, name='delete-product'),
    # RESERVATION.
    path('dashboard/reservation/create/', views.create_reservation, name='create-reservation'),
    path('dashboard/reservation/view/<int:pk>', views.view_reservation, name='view-reservation'),
    path('dashboard/reservation/update/<int:pk>', views.update_reservation, name='update-reservation'),
    path('dashboard/reservation/delete/<int:pk>', views.delete_reservation, name='delete-reservation'),
    # IMPORTATION.
    path('dashboard/importation/create/', views.create_importation, name='create-importation'),
    path('dashboard/importation/view/<int:pk>', views.view_importation, name='view-importation'),
    # ORDER.
    path('dahsboard/order/view/<int:pk>', views.view_order, name='view-order'),
    path('dahsboard/order/confirm/<int:pk>', views.confirm_order, name='confirm-order'),
    path('dahsboard/order/deliver/<int:pk>', views.deliver_order, name='deliver-order')
]

source/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    # ORDER.
    path('<int:choice>', views.order_page, name="order-page"),
    path('cancel-order/<int:pk>', views.cancel_order, name='cancel-order'),
    # PRODUCT DETAIL.
    path('buy-now/', views.buy_now, name='buy-now'),
    path('product/<int:pk>', views.product_detail, name='product'),
    path('purchase-cart/<int:pk>', views.purchase_cart, name='purchase-cart'),
    # CART.
    path('cart/', views.cart_page, name='cart-page'),
    path('create-cart/<int:pk>', views.create_cart, name='create-cart'),
    path('update-cart/<int:pk>', views.update_cart, name='update-cart'),
    path('delete-cart/<int:pk>', views.delete_cart, name='delete-cart'),
    path('create-order/', views.create_order, name="create-order")
]

source/webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('profiles.urls')),
    path('orders/', include('orders.urls')),
    path('controls/', include('controls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/controls/models.py
from datetime import datetime, timedelta

from django.db import models
from django.db.models import Q
from profiles.models import Customer, Employee


class Specification(models.Model):
    os = models.CharField(max_length=200)
    ram = models.CharField(max_length=200)
    cpu = models.CharField(max_length=200)
    disk = models.CharField(max_length=200)
    vga = models.CharField(max_length=200)
    battery = models.FloatField()
    screensize = models.FloatField()
    resolution = models.CharField(max_length=50)
    weight = models.FloatField()

    class Meta:
        unique_together = ('os', 'ram', 'cpu', 'disk', 'vga', 'battery', 'screensize', 'resolution', 'weight')

    def __str__(self) -> str:
        return f'{self.os} - {self.ram} - {self.cpu}'


class Manufacturer(models.Model):
    name = models.CharField(max_length=100, unique=True)
    specifications = models.ManyToManyField(
        Specification, related_name='manufacturers',
        through="LaptopModel", through_fields=('manufacturer', 'specification'))

    def __str__(self) -> str:
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class LaptopModel(models.Model):
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.PROTECT)
    specification = models.ForeignKey(Specification, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='products/', default='img/default.jpg')
    quantity = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=15, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    cart_details = models.ManyToManyField(
        Customer, related_name='cart_details', through='CartDetails',
        through_fields=('laptop_model', 'customer'))

    class Meta:
        ordering = ['-id']
        constraints = [models.CheckConstraint(check=Q(price__gt=0), name='CK_MODEL_PRICE'),
                       models.CheckConstraint(check=Q(quantity__gte=0), name='CK_MODEL_QUANTITY')]

    def __str__(self) -> str:
        return f'{self.name} - {self.specification.pk}'

    def can_delete(self) -> bool:
        return not self.reservationdetails_set.all()


class CartDetails(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    laptop_model = models.ForeignKey(LaptopModel, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    class Meta:
        constraints = [models.CheckConstraint(check=Q(quantity__gt=0), name='CK_CART_QUANTITY')]


class Supplier(models.Model):
    name = models.CharField(max_length=100, unique=True)
    address = models.TextField(null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=25, null=True, blank=True)

    def __str__(self) -> str:
        return self.name


class ReservationForm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.PROTECT)
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    reservation_details = models.ManyToManyField(
        LaptopModel, blank=True, through='ReservationDetails',
        through_fields=('reservation_form', 'laptop_model'))

    class Meta:
        ordering = ['-created']

    @property
    def total(self) -> float:
        return sum([detail.quantity * detail.price for detail in
                    ReservationDetails.objects.filter(reservation_form=self)])

    @property
    def can_delete(self) -> bool:
        return not ImportationForm.objects.filter(reservation_form=self)


class ReservationDetails(models.Model):
    reservation_form = models.ForeignKey(ReservationForm, on_delete=models.CASCADE)
    laptop_model = models.ForeignKey(LaptopModel, on_delete=models.PROTECT)
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)

    class Meta:
        constraints = [models.CheckConstraint(check=Q(quantity__gt=0), name='CK_RESERVATION_DETAILS_QUANTITY')]


class ImportationForm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    reservation_form = models.OneToOneField(ReservationForm, on_delete=models.PROTECT)
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    importation_details = models.ManyToManyField(
        ReservationDetails, through='ImportationDetails',
        through_fields=('importation_form', 'reservations_detail'))

    class Meta:
        ordering = ['-created']

    @property
    def total(self) -> float:
        return sum([detail.quantity * detail.reservations_detail.price for detail in
                    ImportationDetails.objects.filter(importation_form=self)])

    @property
    def can_delete(self) -> bool:
        return datetime.today().timestamp() < (self.created + timedelta(days=1)).timestamp()

    def can_update(self, details: list[str, int]) -> bool:
        for detail_id, quantity in details:
            detail = ReservationDetails.objects.get(pk=detail_id)
            model = detail.laptop_model
            if importation_detail := ImportationDetails.objects.filter(reservations_detail=detail).first():
                if model.quantity + quantity - importation_detail.quantity:
                    return False
        return True


class ImportationDetails(models.Model):
    importation_form = models.ForeignKey(ImportationForm, on_delete=models.CASCADE)
    reservations_detail = models.ForeignKey(ReservationDetails, on_delete=models.PROTECT)
    quantity = models.IntegerField()

    class Meta:
        constraints = [models.CheckConstraint(check=Q(quantity__gt=0), name='CK_IMPORTATION_DETAILS_QUANTITY')]

    def can_delete(self, quantity: int) -> bool:
        return self.reservations_detail.laptop_model.quantity - quantity > 0


class LiquidationForm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    reason = models.TextField()
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)


class Laptop(models.Model):
    is_sold = models.BooleanField(default=False)
    laptop_model = models.ForeignKey(LaptopModel, on_delete=models.PROTECT)
    importation_form = models.ForeignKey(ImportationForm, on_delete=models.PROTECT)
    liquidation_form = models.OneToOneField(LiquidationForm, on_delete=models.PROTECT, null=True, blank=True)

source/orders/models.py
from django.db import models
from django.db.models import Q
from profiles.models import Customer, Employee
from controls.models import Laptop


class DeliveryAddress(models.Model):
    fullname = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.CharField(max_length=25)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)


class State(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    address = models.TextField()
    state = models.ForeignKey(State, on_delete=models.PROTECT, default=1)
    confirm_employee = models.ForeignKey(
        Employee, on_delete=models.PROTECT, null=True, blank=True, related_name='confirm_orders')
    deliver_employee = models.ForeignKey(
        Employee, on_delete=models.PROTECT, null=True, blank=True, related_name='deliver_orders')
    laptops = models.ManyToManyField(
        Laptop, related_name='orders', through='OrderDetails', through_fields=('order', 'laptop'))

    class Meta:
        ordering = ['-created']

    @property
    def total(self) -> float:
        return sum([detail.price for detail in OrderDetails.objects.filter(order=self)])


class OrderDetails(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.PROTECT)

    class Meta:
        constraints = [models.CheckConstraint(check=Q(price__gt=0), name='CK_ORDER_PRICE')]


class ReturnForm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    reason = models.TextField()
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    order = models.OneToOneField(Order, on_delete=models.PROTECT)
    return_details = models.ManyToManyField(
        OrderDetails, through='ReturnDetails', through_fields=('return_form', 'order_detail'))


class ReturnDetails(models.Model):
    return_form = models.ForeignKey(ReturnForm, on_delete=models.CASCADE)
    order_detail = models.ForeignKey(OrderDetails, on_delete=models.PROTECT)

source/controls/forms.py
from django import forms

from profiles.models import Employee
from .models import LaptopModel, Specification


class SpecificationForm(forms.ModelForm):
    os = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    ram = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    cpu = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    disk = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    vga = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    battery = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input'
    }))

    screensize = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'list': 'screensize-list'
    }))

    resolution = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    weight = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input'
    }))

    class Meta:
        model = Specification
        fields = '__all__'


class ModelForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }), required=True)

    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'readonly': True, 'value': 0
    }), required=False)

    price = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'min': 0
    }), required=True)

    class Meta:
        model = LaptopModel
        fields = '__all__'
        exclude = ['cart_details', 'category', 'manufacturer', 'specification']


class EmployeeForm(forms.ModelForm):
    last_name = forms.CharField(label='Họ', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    first_name = forms.CharField(label='Tên', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    gender = forms.BooleanField(label='Giới tính', widget=forms.RadioSelect(attrs={
        'class': 'flex ml-4 gap-10'
    }, choices=((True, 'Nam'), (False, 'Nữ'))), required=False)

    birthdate = forms.DateField(label='Ngày sinh', widget=forms.DateInput(attrs={
        'type': 'date', 'class': 'dashboard-input w-full'
    }), required=True)

    address = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    phone_number = forms.CharField(label='Số điện thoại', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    salary = forms.FloatField(label='Lương', widget=forms.NumberInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    is_quit = forms.BooleanField(
        label='Đã nghỉ', widget=forms.CheckboxInput(), required=False)

    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user']

source/controls/templates/dashboard/product.html
{% extends "components/component.html" %}
{% load static %}
{% load humanize %}

{% block tool %}
	{% include "components/search.html" with type="controls:product" %}
	{% if not request.user.is_superuser %}
		<a href="{% url "controls:create-product" %}" class="hover:text-green-500"><i class="fa-regular fa-square-plus text-3xl"></i></a>
		<a href="{% url "controls:create-specification" %}" class="hover:text-green-500"><i class="fa-solid fa-gear text-3xl"></i></a>
	{% endif %}
	{% if action %}
		<a href="{% url "controls:product" %}">
			<i class="fa-solid fa-right-from-bracket text-2xl hover:text-red-500"></i>
		</a>
	{% endif %}
{% endblock tool %}

{% block table %}
	{% if not action %}
		<div class="rounded-lg overflow-hidden">
			<table class="min-w-full text-xs">
				<thead class="dark:bg-gray-700">
					<tr class="text-left">
						<th class="w-[5%] p-3"></th>
						<th class="w-[25%] p-3">Tên sản phẩm</th>
						<th class="w-[15%] p-3">Danh mục</th>
						<th class="w-[10%] p-3">Số lượng</th>
						<th class="w-[10%] p-3 text-right">Giá bán</th>
						<th class="w-[15%] p-3 text-right">Trạng thái</th>
						<th class="w-[20%] p-3 text-center">Thao tác</th>
					</tr>
				</thead>
				<tbody>
					{% for result in results %}
						<tr class="border-b border-opacity-20 dark:border-gray-700 dark:bg-gray-900">
							<td class="p-3 {% if request.user.is_superuser %}pointer-events-none text-gray-500{% endif %}">
								<form action="{% url "controls:delete-product" result.pk %}" class="text-center {% if not result.can_delete %}pointer-events-none text-gray-500{% endif %}">
									<button class="delete hover:text-red-500">
										<i class="fa-regular fa-rectangle-xmark text-xl"></i>
									</button>
								</form>
							</td>
							<td class="p-3">
								<p>{{ result }}</p>
							</td>
							<td class="p-3">
								<p>{{ result.category.name }}</p>
							</td>
							<td class="p-3 dark:text-gray-400">
								<p>{{ result.quantity }}</p>
							</td>
							<td class="p-3 dark:text-gray-400 text-right">
								<p>{{ result.price | floatformat:0 | intcomma }}</p>
							</td>
							<td class="p-3 text-right italic">
								{% if result.quantity == 0 %}
									<span class="px-3 py-1 rounded-full font-semibold rounded-mdtext-white bg-red-500">
										Hết hàng
									</span>
								{% endif %}
							</td>
							<td class="p-3 {% if request.user.is_superuser %}pointer-events-none text-gray-500{% endif %}">
								<form action="{% url "controls:update-product" result.pk %}" class="text-center">
									<button class="hover:text-sky-500">
										<i class="fa-regular fa-pen-to-square text-2xl"></i>
									</button>
								</form>
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	{% else %}
		{% if result %}
			{% include "components/delete.html" with type="controls:delete-product" name=result.name %}
		{% else %}
			<div class="p-5 bg-gray-200 rounded-md overflow-hidden text-black">
				{% if task == 0 %}
					<form action="" method="post" enctype="multipart/form-data" class="flex flex-col gap-5">
						{% csrf_token %}

						<div class="space-y-5 text-sm mx-auto">
							<div class="max-w-[192px] max-h-32 rounded-md overflow-hidden">
								<img src="" alt="" class="object-contain rounded-md mx-auto">
							</div>
							{{ form.image }}
						</div>
						<div class="space-y-4">
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Tên model</label>
								{{ form.name }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Số lượng tồn</label>
								{{ form.quantity }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Giá bán</label>
								{{ form.price }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Nhà sản xuất</label>
								<input type="text" name="manufacturer" class="dashboard-input" list="manufacturer-list" value="{{ manufacturer }}">
								<datalist id="manufacturer-list">
									<select>
										{% for manufacturer in manufactures %}
											<option value="{{ manufacturer.name }}">{{ manufacturer.name }}</option>
										{% endfor %}
									</select>
								</datalist>
							</div>
							<!-- Specification -->
							<div class="text-white text-xs">
								<div class="border-b border-opacity-20 dark:border-gray-700 dark:bg-gray-900 flex items-center">
									<div class="p-3 w-[12.5%]">
										<input type="text" id="os" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Hệ điều hành">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="text" id="ram" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Bộ nhớ RAM">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="text" id="cpu" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Bộ xử lý trung tâm">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="text" id="disk" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Ổ đĩa">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="text" id="vga" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Card đồ họa">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="text" id="screen" class="p-2 w-full rounded-md placeholder:italic placeholder:normal-case outline-none text-black lowercase" placeholder="Kích thước - Độ phân giải màn hình">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="number" id="battery" class="p-2 w-full rounded-md outline-none placeholder:italic placeholder:normal-case text-black lowercase" placeholder="Năng lượng (h)">
									</div>
									<div class="p-3 w-[12.5%]">
										<input type="number" id="weight" class="p-2 w-full rounded-lg outline-none placeholder:italic placeholder:normal-case text-black lowercase" placeholder="Trọng lượng (g)">
									</div>
								</div>
								<ul class="dark:bg-gray-700 flex min-w-full font-bold">
									<li class="w-[5%] p-3"></li>
									<li class="w-[11.875%] p-3">OS</li>
									<li class="w-[10%] p-3">RAM</li>
									<li class="w-[14.5%] p-3">CPU</li>
									<li class="w-[10%] p-3">Ổ đĩa</li>
									<li class="w-[14.875%] p-3">Card đồ họa</li>
									<li class="w-[13.75%] py-3">Màn hình</li>
									<li class="w-[10%] py-3">Năng lượng</li>
									<li class="w-[10%] py-3">Trọng lượng</li>
								</ul>
								<div class="min-h-[500px] max-h-[500px] overflow-y-auto bg-gray-900 leading-5">
									{% if main %}
										<div class="specification border-b border-opacity-20 dark:border-gray-700 dark:bg-gray-900 flex items-center">
											<div class="p-3 text-center w-[5%]">
												<input type="radio" name="specification" value="{{ main.pk }}" required checked>
											</div>
											<div class="os p-3 w-[11.875%]">
												{{ main.os }}
											</div>
											<div class="ram p-3 w-[10%]">
												{{ main.ram }}
											</div>
											<div class="cpu p-3 w-[14.5%]">
												{{ main.cpu }}
											</div>
											<div class="disk p-3 w-[10%]">
												{{ main.disk }}
											</div>
											<div class="vga p-3 w-[14.875%]">
												{{ main.vga }}
											</div>
											<div class="screen p-3 w-[13.75%]">
												{{ main.screensize }} - {{ main.resolution }}
											</div>
											<div class="battery p-3 w-[10%]">
												{{ main.battery }}
											</div>
											<div class="weight p-3 w-[10%]">
												{{ main.weight }}
											</div>
										</div>
									{% endif %}
									{% for specification in specifications %}
										<div class="specification border-b border-opacity-20 dark:border-gray-700 dark:bg-gray-900 flex items-center">
											<div class="p-3 text-center w-[5%]">
												<input type="radio" name="specification" value="{{ specification.pk }}" required>
											</div>
											<div class="os p-3 w-[11.875%]">
												{{ specification.os }}
											</div>
											<div class="ram p-3 w-[10%]">
												{{ specification.ram }}
											</div>
											<div class="cpu p-3 w-[14.5%]">
												{{ specification.cpu }}
											</div>
											<div class="disk p-3 w-[10%]">
												{{ specification.disk }}
											</div>
											<div class="vga p-3 w-[14.875%]">
												{{ specification.vga }}
											</div>
											<div class="screen p-3 w-[13.75%]">
												{{ specification.screensize }} - {{ specification.resolution }}
											</div>
											<div class="battery p-3 w-[10%]">
												{{ specification.battery }}
											</div>
											<div class="weight p-3 w-[10%]">
												{{ specification.weight }}
											</div>
										</div>
									{% endfor %}
								</div>
							</div>
						</div>
						<button type="submit" class="mt-5 w-1/6 mx-auto text-green-500 bg-white px-5 py-2 rounded-md hover:bg-green-500 hover:text-white italic">
							Xác nhận
						</button>
					</form>
				{% else %}
					<form action="" method="post" class="flex flex-col gap-5">
						{% csrf_token %}
						<div class="space-y-4">
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">OS</label>
								{{ form.os }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">RAM</label>
								{{ form.ram }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">CPU</label>
								{{ form.cpu }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Ổ đĩa</label>
								{{ form.disk }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">VGA</label>
								{{ form.vga }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Năng lượng</label>
								{{ form.battery }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Kích thước màn hình</label>
								{{ form.screensize }}
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Độ phân giải màn hình</label>
								{{ form.resolution }}
								<datalist id="screensize-list">
									<select>
										<option value="13.3">13.3</option>
										<option value="14">14</option>
										<option value="15.6">15.6</option>
									</select>
								</datalist>
							</div>
							<div class="flex justify-between items-center">
								<label for="" class="text-sm italic">Trọng lượng</label>
								{{ form.weight }}
							</div>
						</div>
						<button type="submit" class="mt-5 w-1/6 mx-auto text-green-500 bg-white px-5 py-2 rounded-md hover:bg-green-500 hover:text-white italic">
							Xác nhận
						</button>
					</form>
				{% endif %}
			</div>
		{% endif %}
	{% endif %}
	<!-- Upload Image -->
	<script>
		var uploadButton = document.querySelector('input[name=image]')

		uploadButton.onchange = function (e) {
			var reader = new FileReader()
			reader.onload = function (file) {
				var imgElement = e.target.parentElement.querySelector('img')
				imgElement.src = file.target.result
			}
			reader.readAsDataURL(e.target.files[0])
		}
	</script>
	<!-- Specification -->
	<script src="{% static "js/specification.js" %}"></script>
{% endblock table %}