source/controls/urls.py
from django.urls import path

from . import views


app_name = 'controls'
urlpatterns = [
    # SYSTEM FUNCTIONS.
    path('dashboard/signin/', views.dashboard_signin, name='signin'),
    path('dashboard/logout/', views.dashboard_logout, name='logout'),
    path('dashboard/change-password/', views.dashboard_password, name='change-password'),
    # DASHBOARD PAGE.
    path('dashboard/employee/', views.dashboard_employee, name='employee'),
    path('dashboard/product/', views.dashboard_product, name='product'),
    path('dashboard/reservation/', views.dashboard_reservation, name='reservation'),
    path('dashboard/importation/', views.dashboard_importation, name='importation'),
    path('dashboard/order/', views.dashboard_order, name='order'),
    # EMPLOYEE.
    path('dashboard/employee/create/', views.create_employee, name='create-employee'),
    path('dashboard/employee/update/<int:pk>', views.update_employee, name='update-employee'),
    # PRODUCT.
    path('dashboard/specification/create/', views.create_specification, name='create-specification'),
    path('dashboard/product/create/', views.create_product, name='create-product'),
    path('dashboard/product/update/<int:pk>', views.update_product, name='update-product'),
    path('dashboard/product/delete/<int:pk>', views.delete_product, name='delete-product'),
    # RESERVATION.
    path('dashboard/reservation/create/', views.create_reservation, name='create-reservation'),
    path('dashboard/reservation/view/<int:pk>', views.view_reservation, name='view-reservation'),
    path('dashboard/reservation/update/<int:pk>', views.update_reservation, name='update-reservation'),
    path('dashboard/reservation/delete/<int:pk>', views.delete_reservation, name='delete-reservation'),
    # IMPORTATION.
    path('dashboard/importation/create/', views.create_importation, name='create-importation'),
    path('dashboard/importation/view/<int:pk>', views.view_importation, name='view-importation'),
    # ORDER.
    path('dahsboard/order/view/<int:pk>', views.view_order, name='view-order'),
    path('dahsboard/order/confirm/<int:pk>', views.confirm_order, name='confirm-order'),
    path('dahsboard/order/deliver/<int:pk>', views.deliver_order, name='deliver-order')
]

source/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    # ORDER.
    path('<int:choice>', views.order_page, name="order-page"),
    path('cancel-order/<int:pk>', views.cancel_order, name='cancel-order'),
    # PRODUCT DETAIL.
    path('buy-now/', views.buy_now, name='buy-now'),
    path('product/<int:pk>', views.product_detail, name='product'),
    path('purchase-cart/<int:pk>', views.purchase_cart, name='purchase-cart'),
    # CART.
    path('cart/', views.cart_page, name='cart-page'),
    path('create-cart/<int:pk>', views.create_cart, name='create-cart'),
    path('update-cart/<int:pk>', views.update_cart, name='update-cart'),
    path('delete-cart/<int:pk>', views.delete_cart, name='delete-cart'),
    path('create-order/', views.create_order, name="create-order")
]

source/webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('profiles.urls')),
    path('orders/', include('orders.urls')),
    path('controls/', include('controls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/controls/forms.py
from django import forms

from profiles.models import Employee
from .models import LaptopModel, Specification


class SpecificationForm(forms.ModelForm):
    os = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    ram = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    cpu = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    disk = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    vga = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    battery = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input'
    }))

    screensize = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'list': 'screensize-list'
    }))

    resolution = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }))

    weight = forms.FloatField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input'
    }))

    class Meta:
        model = Specification
        fields = '__all__'


class ModelForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'dashboard-input'
    }), required=True)

    quantity = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'readonly': True, 'value': 0
    }), required=False)

    price = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'dashboard-input', 'min': 0
    }), required=True)

    class Meta:
        model = LaptopModel
        fields = '__all__'
        exclude = ['cart_details', 'category', 'manufacturer', 'specification']


class EmployeeForm(forms.ModelForm):
    last_name = forms.CharField(label='Họ', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    first_name = forms.CharField(label='Tên', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    gender = forms.BooleanField(label='Giới tính', widget=forms.RadioSelect(attrs={
        'class': 'flex ml-4 gap-10'
    }, choices=((True, 'Nam'), (False, 'Nữ'))), required=False)

    birthdate = forms.DateField(label='Ngày sinh', widget=forms.DateInput(attrs={
        'type': 'date', 'class': 'dashboard-input w-full'
    }), required=True)

    address = forms.CharField(label='Địa chỉ', widget=forms.Textarea(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    phone_number = forms.CharField(label='Số điện thoại', widget=forms.TextInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    salary = forms.FloatField(label='Lương', widget=forms.NumberInput(attrs={
        'class': 'dashboard-input w-full'
    }), required=True)

    is_quit = forms.BooleanField(
        label='Đã nghỉ', widget=forms.CheckboxInput(), required=False)

    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ['user']

source/controls/views.py
from math import ceil

from webapps import sessions
from django.http import HttpRequest
from django.contrib.auth import login, logout
from django.shortcuts import render, redirect, get_object_or_404
# DATA.
from django.db.models import Q
from django.db.transaction import atomic
from profiles.models import Employee, User
from profiles.forms import SignInForm
from orders.models import Order, OrderDetails, State
from . import models, forms
# PERMISSION.
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import AbstractBaseUser
# AI MODEL.
from .classification import make_predict


# HOME PAGE.
def home_page(request: HttpRequest):
    user = request.user
    if user.is_authenticated and (user.is_superuser or user.is_staff or user.is_shipper):
        logout(request)
        return redirect('signin')
    # CREATE CONTEXT.
    context = {}
    # GET DATA.
    categories = models.Category.objects.all()
    manufacturers = models.Manufacturer.objects.all()
    all_models = models.LaptopModel.objects.filter(quantity__gt=0)
    # GET CART & ADDRESS.
    if request.user.is_authenticated:
        cart_models = request.user.customer.cart_details.all()
        addresses = request.user.customer.deliveryaddress_set.all()
        context.update({'cart_models': cart_models, 'addresses': addresses})
    # FILTER.
    if kw := request.GET.get('kw', ''):
        all_models = all_models.filter(
            Q(name__icontains=kw) | Q(category__name__icontains=kw) |
            Q(manufacturer__name__icontains=kw) | Q(specification__os__icontains=kw) |
            Q(specification__ram__icontains=kw) | Q(specification__cpu__icontains=kw) |
            Q(specification__disk__icontains=kw) | Q(specification__vga__icontains=kw) |
            Q(specification__battery__icontains=kw) | Q(specification__weight__icontains=kw) |
            Q(specification__screensize__icontains=kw) | Q(specification__resolution__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(all_models) / 12)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    current_page = max(min(current_page, total_pages), 1)
    all_models = all_models[(current_page - 1) * 12:current_page * 12]
    # UPDATE CONTEXT.
    context.update({
        'categories': categories, 'manufacturers': manufacturers,
        'total_pages': total_pages, 'current_page': current_page,
        'show_models': all_models, 'keyword': kw, **sessions.get(request)
    })

    return render(request, 'home.html', context)


# DASHBOARD.
def dashboard_signin(request: HttpRequest):
    user = request.user
    if user.is_authenticated:
        if user.is_superuser:
            return redirect('controls:employee')
        if user.is_staff:
            return redirect('controls:product')

    form = SignInForm(request)
    if request.method == 'POST':
        form = SignInForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            if user.is_staff or user.is_superuser:
                login(request, user)
                if user.is_superuser:
                    return redirect('controls:employee')
                if user.is_staff:
                    return redirect('controls:product')
            else:
                sessions.add(request, 'Đăng nhập thất bại', 'Tài khoản của bạn không có quyền truy cập', False)
        else:
            sessions.add(request, 'Đăng nhập thất bại', 'Thông tin không chính xác', False)

    context = {'form': form, **sessions.get(request)}
    return render(request, 'controls/signin.html', context)


def check_staff_permission(user: AbstractBaseUser) -> bool:
    return user.is_authenticated and (user.is_superuser or user.is_staff)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_password(request: HttpRequest):
    if request.method == 'POST':
        user = request.user
        password = request.POST.get('password')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if password1 != password2:
            sessions.add(request, 'Thao tác thất bại', 'Mật khẩu xác nhận không trùng khớp', False)
        elif not user.check_password(password):
            sessions.add(request, 'Thao tác thất bại', 'Mật khẩu cũ không chính xác', False)
        else:
            user.set_password(password1)
            user.save()
            login(request, user)
            sessions.add(request, 'Thao tác thành công', 'Thay đổi mật khẩu thành công')

    context = {'section': 5, **sessions.get(request)}
    return render(request, 'controls/dashboard.html', context)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_logout(request: HttpRequest):
    logout(request)
    return redirect('controls:signin')


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_employee(request: HttpRequest):
    results = Employee.objects.all()
    # FILTER.
    if kw := request.GET.get('kw', ''):
        results = results.filter(Q(pk__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(results) / 10)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    results = results[(current_page - 1) * 10:current_page * 10]

    context = {'section': 0, 'results': results, 'keyword': kw,
               'total_pages': total_pages, 'current_page': current_page}
    return render(request, 'controls/dashboard.html', context)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_product(request: HttpRequest):
    results = models.LaptopModel.objects.all()
    # FILTER.
    if kw := request.GET.get('kw', ''):
        results = results.filter(
            Q(pk__icontains=kw) | Q(name__icontains=kw) | 
            Q(category__name__icontains=kw) | Q(manufacturer__name__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(results) / 10)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    results = results[(current_page - 1) * 10:current_page * 10]

    context = {'section': 1, 'results': results, 'keyword': kw,
               'total_pages': total_pages, 'current_page': current_page}
    return render(request, 'controls/dashboard.html', context)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_reservation(request: HttpRequest):
    user = request.user
    results = models.ReservationForm.objects.all()
    if not user.is_superuser and user.is_staff:
        results = results.filter(employee=user.employee)
    # FILTER.
    if kw := request.GET.get('kw', ''):
        results = results.filter(Q(pk__icontains=kw) | Q(supplier__name__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(results) / 10)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    results = results[(current_page - 1) * 10:current_page * 10]

    context = {'section': 2, 'results': results, 'keyword': kw,
               'total_pages': total_pages, 'current_page': current_page}
    return render(request, 'controls/dashboard.html', context)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_importation(request: HttpRequest):
    user = request.user
    results = models.ImportationForm.objects.all()
    if not user.is_superuser and user.is_staff:
        results = results.filter(employee=request.user.employee)
    # FILTER.
    if kw := request.GET.get('kw', ''):
        results = results.filter(Q(pk__icontains=kw) | Q(reservation_form__supplier__name__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(results) / 10)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    results = results[(current_page - 1) * 10:current_page * 10]

    context = {'section': 3, 'results': results, 'keyword': kw,
               'total_pages': total_pages, 'current_page': current_page}
    return render(request, 'controls/dashboard.html', context)


@user_passes_test(test_func=check_staff_permission, login_url='signin')
def dashboard_order(request: HttpRequest):
    user = request.user
    results = Order.objects.all()
    if not user.is_superuser and user.is_staff:
        results = results.filter(Q(confirm_employee=None) | Q(confirm_employee=user.employee))
    # FILTER.
    if kw := request.GET.get('kw', ''):
        results = results.filter(Q(pk__icontains=kw))
    # PAGINATE.
    total_pages = ceil(len(results) / 10)
    control_page = int(request.GET.get('control', 0))
    current_page = int(request.GET.get('current_page', 1)) + control_page
    current_page = max(min(current_page, total_pages), 1)
    results = results[(current_page - 1) * 10:current_page * 10]

    context = {'section': 4, 'results': results, 'keyword': kw,
               'total_pages': total_pages, 'current_page': current_page}
    return render(request, 'controls/dashboard.html', context)


# EMPLOYEE.
@user_passes_test(test_func=check_staff_permission, login_url='signin')
@atomic
def create_employee(request: HttpRequest):
    form = forms.EmployeeForm()

    if request.method == 'POST':
        form = forms.EmployeeForm(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        role = request.POST.get('role')

source/controls/templates/controls/dashboard.html
{% extends "base.html" %}
{% load static %}


{% block title %}Quản trị viên{% endblock title %}

{% block content %}
    <div class="max-w-full min-h-screen font-main">
        <!-- Navigation -->
        <nav class="h-20 bg-gray-800 flex justify-between items-center px-10">
            <!-- Tools -->
            <ul class="flex items-center text-white text-sm gap-7">
                <li>
                    <img class="h-10" src="{% static "img/logo.svg" %}" alt="">
                </li>
                {% if request.user.is_superuser %}
                    <li class="bg-gray-900 px-5 py-2 rounded-md hover:bg-gray-700 {% if section == 0 %}bg-white text-black{% endif %}">
                        <a href="{% url "controls:employee" %}">Nhân viên</a>
                    </li>
                {% endif %}
                <li class="bg-gray-900 px-5 py-2 rounded-md hover:bg-gray-700 {% if section == 1 %}bg-white text-black{% endif %}">
                    <a href="{% url "controls:product" %}">Sản phẩm</a>
                </li>
                <li class="bg-gray-900 px-5 py-2 rounded-md hover:bg-gray-700 {% if section == 2 %}bg-white text-black{% endif %}">
                    <a href="{% url "controls:reservation" %}">Phiếu đặt</a>
                </li>
                <li class="bg-gray-900 px-5 py-2 rounded-md hover:bg-gray-700 {% if section == 3 %}bg-white text-black{% endif %}">
                    <a href="{% url "controls:importation" %}">Phiếu nhập</a>
                </li>
                <li class="bg-gray-900 px-5 py-2 rounded-md hover:bg-gray-700 {% if section == 4 %}bg-white text-black{% endif %}">
                    <a href="{% url "controls:order" %}">Đơn đặt hàng</a>
                </li>
            </ul>
            <!-- Profile -->
            <div class="text-white text-2xl space-x-5">
                <a href="{% url "controls:logout" %}" class="hover:text-indigo-600">
                    <i class="fa-solid fa-right-from-bracket text-2xl"></i>
                </a>
                <a href="{% url "controls:change-password" %}" class="hover:text-indigo-600">
                    <i class="fa-solid fa-key text-2xl"></i>
                </a>
                <i class="fa-solid fa-user-gear"></i>
            </div>
        </nav>
        <!-- Display -->
        <div class="w-full my-5">
            {% if section == 0 %}
                {% include "dashboard/employee.html" %}
            {% elif section == 1 %}
                {% include "dashboard/product.html" %}
            {% elif section == 2 %}
                {% include "dashboard/reservation.html" %}
            {% elif section == 3 %}
                {% include "dashboard/importation.html" %}
            {% elif section == 4 %}
                {% include "dashboard/order.html" %}
            {% else %}
                {% include "controls/password.html" %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

source/controls/templates/controls/password.html
<!-- Form -->
<form action="{% url "controls:change-password" %}" method="post" class="w-3/5 py-3 flex flex-col gap-5 mx-auto">
    {% csrf_token %}
    <input type="hidden" name="choice" value={{ choice }}>

    <table class="border-separate border-spacing-4">
        <tr>
            <td class="text-right">Mật khẩu cũ: </td>
            <td><input type="password" name="password" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
        <tr>
            <td class="text-right">Mật khẩu mới: </td>
            <td><input type="password" name="password1" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
        <tr>
            <td class="text-right">Mật khẩu xác nhận: </td>
            <td><input type="password" name="password2" class="border-2 rounded-md p-2 w-96" required></td>
        </tr>
    </table>

    <button type="submit" class="w-1/4 mx-auto mt-5 p-2 rounded-lg bg-sky-300 text-white hover:shadow-lg">
        <i class="fa-solid fa-cloud-arrow-up"></i> Lưu
    </button>
</form>

source/controls/templates/controls/signin.html
{% extends "base.html" %}
{% load static %}


{% block title %}Đăng nhập{% endblock title %}

{% block content %}
<div class="log-form-control">
    <form action="" method="post" class="log-form">
        {% csrf_token %}
        <div class="mb-10">
            <img src="{% static "img/logo.svg" %}" alt="Logo" class="w-20 mx-auto">
            <h1 class="text-4xl text-center font-serif font-semibold">ADMINISTRATOR</h1>
        </div>

        <div class="my-5 space-y-7">
            <div class="log-input-group">
                <i class="fa-solid fa-user log-input-icon"></i>
                {{ form.username }}
            </div>
    
            <div class="log-input-group">
                <i class="fa-solid fa-lock log-input-icon"></i>
                {{ form.password }}
            </div>
        </div>

        <button type="submit" class="log-button">SIGN IN</button>
    </form>
</div>
{% endblock content %}