source/orders/urls.py
from django.urls import path

from . import views


app_name = 'orders'
urlpatterns = [
    # ORDER.
    path('<int:choice>', views.order_page, name="order-page"),
    path('cancel-order/<int:pk>', views.cancel_order, name='cancel-order'),
    # PRODUCT DETAIL.
    path('buy-now/', views.buy_now, name='buy-now'),
    path('product/<int:pk>', views.product_detail, name='product'),
    path('purchase-cart/<int:pk>', views.purchase_cart, name='purchase-cart'),
    # CART.
    path('cart/', views.cart_page, name='cart-page'),
    path('create-cart/<int:pk>', views.create_cart, name='create-cart'),
    path('update-cart/<int:pk>', views.update_cart, name='update-cart'),
    path('delete-cart/<int:pk>', views.delete_cart, name='delete-cart'),
    path('create-order/', views.create_order, name="create-order")
]

source/webapps/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('profiles.urls')),
    path('orders/', include('orders.urls')),
    path('controls/', include('controls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/orders/models.py
from django.db import models
from django.db.models import Q
from profiles.models import Customer, Employee
from controls.models import Laptop


class DeliveryAddress(models.Model):
    fullname = models.CharField(max_length=100)
    address = models.TextField()
    phone = models.CharField(max_length=25)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)


class State(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self) -> str:
        return self.name


class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    address = models.TextField()
    state = models.ForeignKey(State, on_delete=models.PROTECT, default=1)
    confirm_employee = models.ForeignKey(
        Employee, on_delete=models.PROTECT, null=True, blank=True, related_name='confirm_orders')
    deliver_employee = models.ForeignKey(
        Employee, on_delete=models.PROTECT, null=True, blank=True, related_name='deliver_orders')
    laptops = models.ManyToManyField(
        Laptop, related_name='orders', through='OrderDetails', through_fields=('order', 'laptop'))

    class Meta:
        ordering = ['-created']

    @property
    def total(self) -> float:
        return sum([detail.price for detail in OrderDetails.objects.filter(order=self)])


class OrderDetails(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    laptop = models.ForeignKey(Laptop, on_delete=models.PROTECT)

    class Meta:
        constraints = [models.CheckConstraint(check=Q(price__gt=0), name='CK_ORDER_PRICE')]


class ReturnForm(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    reason = models.TextField()
    employee = models.ForeignKey(Employee, on_delete=models.PROTECT)
    order = models.OneToOneField(Order, on_delete=models.PROTECT)
    return_details = models.ManyToManyField(
        OrderDetails, through='ReturnDetails', through_fields=('return_form', 'order_detail'))


class ReturnDetails(models.Model):
    return_form = models.ForeignKey(ReturnForm, on_delete=models.CASCADE)
    order_detail = models.ForeignKey(OrderDetails, on_delete=models.PROTECT)

source/orders/views.py
from webapps import sessions
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect
# DATA.
from django.db.transaction import atomic
from controls.models import LaptopModel, CartDetails, Laptop
from . import models
# PERMISSION.
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.decorators import user_passes_test


def check_customer_permission(user: AbstractBaseUser) -> bool:
    return user.is_authenticated and not (user.is_superuser or user.is_staff or user.is_shipper)


# ORDER.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def order_page(request: HttpRequest, choice: int):
    customer = request.user.customer
    orders = models.Order.objects.filter(customer=customer)
    cart_models = customer.cart_details.all()
    states = models.State.objects.all()
    # FILTER BY STATE.
    if choice != 0:
        orders = orders.filter(state__pk=choice)
    # FILTER BY ORDER ID.
    if kw := request.GET.get('kw'):
        orders = orders.filter(pk=int(kw))
    # ORDER RESULT.
    result = []
    for order in orders:
        order_details = models.OrderDetails.objects.filter(order=order)
        # ORDER TOTAL.
        total = sum(map(lambda detail: detail.price, order_details))
        # ORDER DETAILS.
        details = []
        for order_detail in order_details:
            detail = [order_detail.laptop.laptop_model, 1, order_detail.price]
            existed_detail = list(filter(lambda e: e[0] == detail[0], details))
            if not existed_detail:
                details.append(detail)
            else:
                details[details.index(existed_detail[0])][1] += 1
        result.append((order, details, total))

    context = {'orders': result, 'states': states, 'choice': choice,
               'cart_models': cart_models, **sessions.get(request)}
    return render(request, 'orders/list.html', context)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
@atomic
def create_order(request: HttpRequest):
    # GET DATA.
    customer = request.user.customer
    details = CartDetails.objects.filter(customer=customer)
    if details:
        fullname = request.POST.get('fullname')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        delivery_address = f'{fullname}, {phone}, {address}'
        # CREATE ORDER.
        order = models.Order.objects.create(customer=customer, address=delivery_address)
        # CREATE ORDER DETAILS.
        for detail in details:
            if detail.laptop_model.quantity > 0:
                model = detail.laptop_model
                for laptop in Laptop.objects.filter(laptop_model=model, is_sold=False)[:detail.quantity]:
                    models.OrderDetails.objects.create(order=order, laptop=laptop, price=model.price)
                    # SOLD LAPTOP.
                    laptop.is_sold = True
                    laptop.save()
                # REDUCE QUANTITY.
                model.quantity -= detail.quantity
                model.save()
        # DELETE ALL CART DETAILS.
        details.delete()
        sessions.add(request, 'Thao tác thành công', 'Đặt hàng thành công')
    else:
        sessions.add(request, 'Thanh toán thất bại', 'Giỏ hàng đang trống', False)

    return redirect('orders:cart-page', permanent=True)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
@atomic
def cancel_order(request: HttpRequest, pk: int):
    # TRANSFORM STATE OF ORDER.
    order = get_object_or_404(models.Order, pk=pk)
    order.state = models.State.objects.get(pk=5)
    order.save()
    # RE-SOLD LAPTOP & RE-INCREASE QUANTITY OF MODEL.
    for laptop in order.laptops.all():
        laptop.is_sold = False
        laptop.laptop_model.quantity += 1
        laptop.laptop_model.save()
        laptop.save()

    sessions.add(request, 'Thao tác thành công', 'Đơn hàng đã được hủy')
    return redirect('orders:order-page', 0)


# CART.
@user_passes_test(test_func=check_customer_permission, login_url='signin')
def cart_page(request: HttpRequest):
    customer = request.user.customer
    addresses = customer.deliveryaddress_set.all()
    cart_models = customer.cart_details.all()
    cart_details = CartDetails.objects.filter(customer=customer)
    total = sum(map(lambda e: e.quantity * e.laptop_model.price * (e.laptop_model.quantity > 0), cart_details))

    context = {'cart_models': cart_models, 'cart_details': cart_details,
               'total': total, 'addresses': addresses, **sessions.get(request)}
    return render(request, 'orders/cart.html', context)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def create_cart(request: HttpRequest, pk: int):
    customer = request.user.customer
    model = get_object_or_404(LaptopModel, pk=pk)
    # CHECK EXIST.
    cart_detail = CartDetails.objects.filter(customer=customer, laptop_model__pk=pk).first()
    if cart_detail:
        if cart_detail.quantity < model.quantity:
            cart_detail.quantity += 1
            cart_detail.save()
    else:
        CartDetails.objects.create(laptop_model=model, customer=customer, quantity=1)
    sessions.add(request, 'Thao tác thành công', 'Hãy kiểm tra giỏ hàng')

    return redirect('orders:product', pk)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def update_cart(request: HttpRequest, pk: int):
    cart_detail = get_object_or_404(CartDetails, pk=pk)
    # INCREASE/DECREASE.
    quantity = cart_detail.quantity + int(request.GET.get('control'))
    if quantity <= cart_detail.laptop_model.quantity:
        # DELETE IF QUANTITY EQUALS TO ZERO.
        if quantity == 0:
            cart_detail.delete()
        else:
            cart_detail.quantity = quantity
            cart_detail.save()
    # ERROR MESSAGE IF QUANTITY IS OVER THE INVENTORY.
    else:
        sessions.add(request, 'Thao tác thất bại', 'Không thể vượt quá số lượng hiện có', False)

    return redirect('orders:cart-page')


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def delete_cart(request: HttpRequest, pk: int):
    cart_detail = get_object_or_404(CartDetails, pk=pk)
    cart_detail.delete()

    return redirect('orders:cart-page')


# PRODUCT.
def product_detail(request: HttpRequest, pk: int):
    model = get_object_or_404(LaptopModel, pk=pk)
    cart_models = request.user.customer.cart_details.all() if request.user.is_authenticated else None

    context = {'model': model, 'cart_models': cart_models, **sessions.get(request)}
    return render(request, 'orders/product.html', context)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
@atomic
def buy_now(request: HttpRequest):
    # GET DATA.
    customer = request.user.customer
    fullname = request.POST.get('HoTen')
    phone = request.POST.get('sdt')
    address = request.POST.get('diaChi')
    delivery_address = f'{fullname}, {phone}, {address}'
    # GET LAPTOP.
    model_id = int(request.POST.get('model'))
    model = LaptopModel.objects.get(pk=model_id)
    laptop = model.laptop_set.filter(is_sold=False).first()
    # CREATE ORDER.
    order = models.Order.objects.create(customer=customer, address=delivery_address)
    # CREATE ORDER DETAIL.
    models.OrderDetails.objects.create(order=order, laptop=laptop, price=model.price)
    # REDUCE QUANTITY.
    model.quantity -= 1
    model.save()
    # SOLD LAPTOP.
    laptop.is_sold = True
    laptop.save()

    return redirect('orders:order-page', 0)


@user_passes_test(test_func=check_customer_permission, login_url='signin')
def purchase_cart(request: HttpRequest, pk: int):
    customer = request.user.customer
    model = get_object_or_404(LaptopModel, pk=pk)
    # CHECK EXIST.
    cart_detail = CartDetails.objects.filter(customer=customer, laptop_model__pk=pk).first()
    if cart_detail:
        if cart_detail.quantity < model.quantity:
            cart_detail.quantity += 1
            cart_detail.save()
    else:
        CartDetails.objects.create(laptop_model=model, customer=customer, quantity=1)

    return redirect('orders:cart-page')

source/orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{% block title %}Giỏ hàng{% endblock title %}

{% block content %}
    {% include "home/header.html" %}
    <section class="w-[90%] mx-auto my-5 flex font-main relative">
        <!-- Address -->
        <form action="{% url "orders:create-order" %}" method="post" class="w-3/5 p-5 min-h-screen border-r border-r-secondary flex flex-col gap-3">
            {% csrf_token %}
            
            <h3 class="text-xl font-extrabold flex justify-between">
                <span>Thông tin vận chuyển</span>
                <button class="changeAddress text-sm font-normal hover:text-sky-400 cursor-pointer">
                    <i class="fa-solid fa-book-atlas"></i> Chọn từ sổ địa chỉ
                </button>
            </h3>
            <div class="py-3 space-y-4">
                <div class="flex justify-between">
                    <input type="text" name="fullname" class="w-[48%] px-5 py-2 border-2 border-gray-400 rounded-2xl placeholder:text-sm" placeholder="Họ tên" required>
                    <input type="tel" name="phone" class="w-[48%] px-5 py-2 border-2 border-gray-400 rounded-2xl placeholder:text-sm" placeholder="Số điện thoại" required>
                </div>
                <input type="email" name="email" class="w-full px-5 py-2 border-2 border-gray-400 rounded-2xl" value="{{ request.user.email }}" disabled>
                <input type="text" name="address" class="w-full px-5 py-2 border-2 border-gray-400 rounded-2xl placeholder:text-sm" placeholder="Địa chỉ giao hàng" required>
            </div>

            <h3 class="mt-5 text-xl font-extrabold">Hình thức thanh toán</h3>
            <ul class="py-3 space-y-4">
                <li  class="px-5 py-2 flex items-center gap-5 border-2 border-gray-400 rounded-xl">
                    <input type="radio" checked readonly class="w-5 h-5">
                    <i class="fa-solid fa-truck text-3xl"></i>
                    <div class="text-primary">
                        <p class="text-sm">COD</p>
                        <p class="text-xs">Thanh toán khi nhận hàng</p>
                    </div>
                </li>
                <li  class="px-5 py-2 flex items-center gap-5 border-2 border-gray-400 rounded-xl">
                    <input type="radio" disabled class="w-5 h-5">
                    <i class="fa-solid fa-credit-card text-3xl"></i>
                    <div class="text-primary">
                        <p class="text-sm">Thanh toán với thẻ tín dụng</p>
                        <p class="text-xs">Thẻ ATM / Thẻ tín dụng (Credit Card) / Thẻ ghi nợ (Debit Card)</p>
                    </div>
                </li>
                <li  class="px-5 py-2 flex items-center gap-5 border-2 border-gray-400 rounded-xl">
                    <input type="radio" disabled class="w-5 h-5">
                    <i class="fa-solid fa-globe text-3xl"></i>
                    <div class="text-primary">
                        <p class="text-sm">Thanh toán quốc tế</p>
                        <p class="text-xs">Thẻ Visa / Thẻ Master</p>
                    </div>
                </li>
                <li  class="px-5 py-2 flex items-center gap-5 border-2 border-gray-400 rounded-xl">
                    <input type="radio" disabled class="w-5 h-5">
                    <i class="fa-solid fa-qrcode text-3xl"></i>
                    <div class="text-primary">
                        <p class="text-sm">Chuyển khoản liên ngân hàng với QR Code</p>
                        <p class="text-xs">Chuyển tiền qua ví điện tử (MoMo, ZaloPay, ...)</p>
                    </div>
                </li>
            </ul>

            <button type="submit" class="w-full p-4 bg-indigo-500 text-white rounded-xl {% if total == 0 %}opacity-50 pointer-events-none{% endif %}">
                Thanh toán ({{ total | floatformat:0 | intcomma }} VNĐ)
            </button>
        </form>
        <!-- Cart Items -->
        <div class="w-2/5 p-5 min-h-screen flex flex-col gap-3">
            <h3 class="text-xl font-extrabold">Giỏ hàng</h3>
            
            <ul class="mt-5 flex flex-col gap-10">
                {% for detail in cart_details %}
                    <li class="flex flex-col sm:flex-row sm:justify-between">
                        <div class="relative flex w-full space-x-3 sm:space-x-4">
                            <a href="{% url "orders:product" detail.laptop_model.pk %}" class="{% if detail.laptop_model.quantity == 0 %}opacity-20 pointer-events-none{% endif %}">
                                <img class="flex-shrink-0 w-48 h-32 object-cover dark:border-transparent rounded outline-none dark:bg-gray-500" src="{{ detail.laptop_model.image }}">
                            </a>
                            {% if detail.laptop_model.quantity == 0 %}
                                <p class="absolute -left-1 top-12 w-28 p-2 rounded-full font-bold bg-yellow-100 text-red-500 text-center -rotate-[30deg] opacity-100">
                                    Hết hàng
                                </p>
                            {% endif %}
                            <div class="flex flex-col justify-between w-full">
                                <div class="flex justify-between w-full pb-2 space-x-2">
                                    <div class="space-y-3">
                                        <h3 class="text-sm font-semibold sm:pr-8 w-52 italic">
                                            {{ detail.laptop_model.name }} - {{ detail.laptop_model.specification.pk }}
                                        </h3>
                                        
                                        <form action="{% url "orders:update-cart" detail.pk %}" class="flex w-fit px-3 py-1 gap-5 border border-primary rounded-lg {% if detail.laptop_model.quantity == 0 %}opacity-20 pointer-events-none{% endif %}">
                                            <button type="submit" name="control" value="-1" >
                                                <i class="fa-solid fa-minus text-xs"></i>
                                            </button>
                                            <p>{{ detail.quantity }}</p>
                                            <button type="submit" name="control" value="1">
                                                <i class="fa-solid fa-plus text-xs"></i>
                                            </button>
                                        </form>

                                        <h3 class="text-sm font-semibold sm:pr-8 w-52 {% if detail.laptop_model.quantity >= 10 %}text-yellow-500{% else %}text-red-500{% endif %} ">
                                            Tối đa: {{ detail.laptop_model.quantity }}
                                        </h3>
                                    </div>
                                    <div class="text-right flex flex-col justify-between">
                                        <a href="{% url "orders:delete-cart" detail.pk %}" class="text-right"><i class="fa-solid fa-xmark"></i></a>
                                        <p class="text-sm font-semibold">
                                            {{ detail.laptop_model.price | floatformat:0 | intcomma }} VNĐ
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </li>
                    {% empty %}
                    <p class="text-center text-sm">Bạn chưa có sản phẩm nào!</p>
                {% endfor %}
            </ul>
        </div>
        <!-- Support Modal -->
        <div class="hidden">
            <div class="flex gap-3 items-center justify-center">
                <span class="w-1/5">Thành phố/Tỉnh: </span>
                <select id="dropdownProv" class="w-3/5 p-2 rounded-md" name="province" required></select>
                <input type="hidden" >
            </div>
            <div class="flex gap-3 items-center justify-center">
                <span class="w-1/5">Quận/Huyện: </span>
                <select id="dropdownDistr" class="w-3/5 p-2 rounded-md" name="district" required></select>
                <input type="hidden" >
            </div>
            <div class="flex gap-3 items-center justify-center">
                <span class="w-1/5">Phường/Xã: </span>
                <select id="dropdownWard" class="w-3/5 p-2 rounded-md" name="commune" required></select>
                <input type="hidden" >
            </div>
        </div>
        <!-- Modal -->
        <div id="myAddressModal" class="modal">
            <div class="modal-content w-1/2 p-0 border-0 bg-gray-500 rounded-md font-main">
                <!-- Title -->
                <p class="title p-3 text-base text-white bg-indigo-600">
                    <i class="fa-solid fa-truck-fast"></i> Địa chỉ giao hàng
                </p>
                <!-- Content -->
                <div class="px-5 my-4 flex flex-col gap-3">
                    {% for address in addresses %}
                        <div class="address border-2 px-3 py-2 bg-white rounded-lg my-2 flex flex-col gap-3">
                            <h3 class="font-bold">
                                <i class="fa-solid fa-user-tag"></i> <span class="fullname">{{ address.fullname }}</span>
                                <span class="ml-3">
                                    <i class="fa-solid fa-phone-volume"></i> <span class="phone">{{ address.phone }}</span>
                                </span>
                            </h3>
                            <p class="italic"><i class="fa-solid fa-street-view"></i> <span class="address">{{ address.address }}</span></p>
                            <button class="changeAddressBtn block ml-auto bg-blue-500 text-white rounded-md px-3 py-2 hover:bg-blue-300 hover:shadow">
                                <i class="fa-solid fa-location-crosshairs"></i> Giao đến đây
                            </button>
                        </div>
                    {% empty %}
                        <p class="text-white p-5 italic text-center">Bạn chưa thiết lập địa chỉ nào!</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    {% include "home/footer.html" %}

    <script src="{% static "js/cart.js" %}"></script>
    <script src="{% static "js/address.js" %}"></script>
{% endblock content %}

source/orders/templates/orders/list.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}Đơn hàng{% endblock title %}

{% block content %}
    {% include "home/header.html" %}
    <section class="w-4/5 mx-auto my-5 font-main">
        <!-- Filter Bar -->
        <ul class="mb-5 flex justify-between text-center">
            <li class="w-1/6 p-2 border-b-4 hover:text-blue-500 hover:border-b-sky-500 {% if choice == 0 %}border-b-sky-500{% else %}border-b-transparent{% endif %}">
                <a href="{% url "orders:order-page" 0 %}">Tất cả đơn</a>
            </li>
            {% for state in states %}
                <li class="w-1/6 p-2 border-b-4 hover:text-blue-500 hover:border-b-sky-500 {% if choice == state.pk %}border-b-sky-500{% else %}border-b-transparent{% endif %}">
                    <a href="{% url "orders:order-page" state.pk %}">{{ state.name }}</a>
                </li>
            {% endfor %}
        </ul>
        <!-- Search Bar -->
        <div class="p-1 border-2 border-solide border-black rounded-md">
            <form action="{% url "orders:order-page" 0 %}" class="flex justify-center items-center">
                <label for="search"><i class="fa-solid fa-magnifying-glass px-3"></i></label>
                <input type="search" name="kw" id="search" placeholder="Nhập mã đơn hàng của bạn" class="w-full p-1 border-none outline-none placeholder:text-sm placeholder:italic">
            </form>
        </div>
        <!-- Order List -->
        <div class="my-5 p-5 rounded-md bg-secondary space-y-5">
            {% for order, details, total in orders %}
                <div class="bg-white rounded-md py-2">
                    <!-- ORDER STATE -->
                    <div class="text-primary px-5 pt-3 flex justify-between">
                        <h2 class="flex items-center gap-3">
                            <i class="fa-solid fa-truck-fast"></i>
                            <p>{{ order.state }}</p>
                        </h2>
                        <h2 class="flex items-center gap-3">
                            <i class="fa-solid fa-circle-info"></i>
                            <p class="text-xs">Đơn hàng: #{{ order.pk }} - Khách hàng: {{ order.address }}</p>
                        </h2>
                    </div>
                    <hr class="mx-auto my-3 w-[95%]">
                    <!-- ORDER PRODUCTS -->
                    <div class="my-4 px-5 space-y-5">
                        {% for model, quantity, price in details %}
                            <div class="flex justify-between">
                                <div class="w-4/5 flex gap-10 relative">
                                    <img class="w-1/5" src="{{ model.image }}" alt="">
                                    <strong>{{ model.name }}</strong>
                                    <div class="absolute left-0 bottom-0 flex justify-center items-center w-10 h-10 rounded-tl-lg rounded-br-lg bg-primary">
                                        <p class="text-white">{{ quantity }}</p>
                                    </div>
                                </div>
                                <p class="w-1/5 text-right">{{ price | floatformat:0 | intcomma }}</p>
                            </div>
                        {% endfor %}
                    </div>
                    <!-- ODER TOTAL -->
                    <hr class="mx-auto my-3 w-[95%]">
                    <div class="px-5 py-3 flex flex-col justify-end items-end gap-3">
                        <p>Tổng tiền: <strong>{{ total | floatformat:0 | intcomma }} VNĐ</strong></p>
                        <!-- TOOLS -->
                        {% if order.state.pk < 3 %}
                            <a href="{% url "orders:cancel-order" order.pk %}" class="block px-5 py-2 rounded-lg border-2 border-red-500 text-red-500 hover:text-white hover:bg-red-500">Hủy đơn hàng</a>
                        {% endif %}
                    </div>
                </div>
                {% empty %}
                <div class="min-h-[20vh] flex flex-col gap-5 justify-center items-center">
                    <h3 class="text-center italic">Bạn không có đơn hàng nào!</h3>
                    <i class="fa-regular fa-face-frown text-2xl"></i>
                </div>
            {% endfor %}
        </div>
    </section>
    {% include "home/footer.html" %}
{% endblock content %}

source/orders/templates/orders/product.html
{% extends 'base.html' %}
{% load humanize %}


{% block title %}{{ model.name }}{% endblock %}

{% block content %}
    {% include "home/header.html" %}
    <section class="my-5 p-5 flex font-main justify-around">
        <!-- Tools -->
        <div class="relative w-2/5">
            <img class="w-[550px] h-[400px] object-contain mx-auto" src="{{ model.image }}" alt="">
            <div class="mt-5 flex justify-center gap-10 text-white">
                <a href="{% url "orders:purchase-cart" model.pk %}" class="p-3 bg-red-500 rounded-xl outline-none hover:ring-2 hover:ring-red-600">
                    <i class="fa-solid fa-credit-card"></i> Thanh toán
                </a>
                <a href="{% url "orders:create-cart" model.pk %}" class="p-3 bg-sky-500 rounded-xl outline-none hover:ring-2 hover:ring-sky-600">
                    <i class="fa-solid fa-cart-flatbed"></i> Thêm vào giỏ hàng
                </a>
                <a title="Quay lại" href="{{ request.META.HTTP_REFERER }}" class="block absolute -left-14 top-0 text-2xl text-black">
                    <i class="fa-solid fa-chevron-left"></i>
                </a>
            </div>
        </div>
        <div class="w-2/5">
            <!-- Model name & Quantity -->
            <strong class="text-lg">
                <p class="flex justify-between items-center">
                    <span class="italic">{{ model.name }} - {{ model.specification.pk }}</span>
                    <span class="text-sm">Số lượng: {{ model.quantity }}</span>
                </p>
                <span class="text-red-500">{{ model.price | floatformat:0 | intcomma }} VNĐ</span>
            </strong>
            <!-- Specifications -->
            <table class="w-full mt-3">
                <caption class="mb-2 caption-top text-sm italic">Thông số kỹ thuật</caption>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Hệ điều hành </th>
                    <td class="pl-10">{{ model.specification.os }}</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">CPU </th>
                    <td class="pl-10">{{ model.specification.cpu }}</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Ổ đĩa </th>
                    <td class="pl-10">{{ model.specification.disk }}</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Card đồ họa </th>
                    <td class="pl-10">{{ model.specification.vga }}</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Năng lượng </th>
                    <td class="pl-10">{{ model.specification.battery }} h</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Màn hình </th>
                    <td class="pl-10">{{ model.specification.screensize }} inches</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Độ phân giải </th>
                    <td class="pl-10">{{ model.specification.resolution }}</td>
                </tr>
                <tr class="h-11 even:bg-gray-300 odd:bg-gray-100">
                    <th class="text-left w-40 pl-5">Trọng lượng </th>
                    <td class="pl-10">{{ model.specification.weight }} kg</td>
                </tr>
            </table>
        </div>
    </section>
    {% include "home/footer.html" %}
{% endblock %}